name: ustpessentials
description: The USTP E-Commerce App is a digital marketplace designed exclusively for students, faculty, and staff of the University of Science and Technology of Southern Philippines (USTP)..

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1  
  shared_preferences: ^2.2.2
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
